version: "3"
services:
  postgres:
    image: "postgres:11.1-alpine"
    expose:
      - "5432"
    env_file:
      - .env_template
    volumes:
      - ../postgres-slpnotify-data:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env_template
    depends_on:
      - postgres
    volumes:
      - ./:/code
  frontend:
    build: 
      context: ./slpnotifyui
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
